### ISSUE TITLE
Add songs error

### ISSUE THREAD

**Issue by wbadart** [mkrum/Jamocracy#1]
John just told me that everyone's getting an error when they try to add a song.  He said there was some error reported.  I checked out your last commit and it looks like some changes were made to your `addSongToPlaylist` function.  I didn't look at it in depth, but it sounds like this could be the source of the issue.  Just wanted to let you guys know.

**Comment by DanielKerrigan** [comment]
Thanks Will. I'm looking into it now.

It has to do with an access token for the Spotify Web API expiring.
