### ISSUE TITLE
Properly replying to incoming messages

### ISSUE THREAD

**Issue by DanielKerrigan** [mkrum/Jamocracy#5]
Right now, we are responding to incoming texts by sending an outgoing message to the number that texted us and then using res.sendStatus() to avoid the HTTP Retrieval Failure Errors from Twilio. 

It seems that res.sendStatus() sends a text message of the status. When I send a song, I first received a text saying “OK” (for res.sendStatus(200)) and then I receive the normal text saying that the song was added. It looks like sending the status costs just as much as sending another message, so I think we should try to avoid having to send two messages each time. Also, using only res.end() doesn't appear to avoid the HTTP retrieval errors, since the errors still occur when someone joins a playlist, in which case we are currently not sending a status and are instead using res.end().

I think the problem is that our sendText function sends a new outgoing text message, which is different than responding to an incoming text. With the exception of sending the party code to the host at the beginning, we should always be responding to texts. I think we should have two different functions. One where we are sending a new text as we currently are and one where we are responding, which is where we would handle the HTTP response to avoid the retrieval errors. I can add that function to our messenger service.

Thoughts?

**Comment by samcal** [comment]
Makes sense to me. What does the API look like on the Twilio side? We can definitely add another function to `MessengerService`, although perhaps it should be in the other direction, renaming the function to send the initial text.

**Comment by DanielKerrigan** [comment]
I think it would basically look like this. I haven't tested it yet.

``` javascript
function respondToText(req, res, msg){
    if(twilio.validateExpressRequest(req, process.env.TWILIO_AUTH_TOKEN)){
        var twiml = new twilio.TwimlResponse()
        twiml.message(msg)
        res.writeHead(200, {'Content-Type': 'text/xml'});
        res.end(twiml.toString());
    } else {
        res.sendStatus(403);
    }
}
```

**Comment by samcal** [comment]
Hm, not super stoked to bring express logic into the MessengerService. Can we move that express-specific logic into the route?

**Comment by DanielKerrigan** [comment]
The validateExpressRequest isn't necessary and could be moved to the route. It would probably make sense to validate it right away in the sms route.

**Comment by samcal** [comment]
Cool, so I'm thinking the MessengerService takes a message and returns the appropriate TwiML as a string, then we set it on the response object back in the route.

**Comment by DanielKerrigan** [comment]
So this in MessengerService:

``` javascript
function getTwiMLString(msg){
    var twiml = new twilio.TwimlResponse()
    twiml.message(msg)
    return twiml.toString()
}
```

Would we then want a function in the sms_route.js like this?

``` javascript
function respondToText(res, msg){
    res.writeHead(200, {'Content-Type': 'text/xml'});
    res.end(MessengerService.getTwiMLString(msg));
}
```

**Comment by samcal** [comment]
Yep, looks good to me 👍 

Maybe also consider adding a function to validate, seems like a good thing to do. Even if it means sending the request into a service, at least the service isn't ending the response for us.

``` javascript
// services/messenger_service.js
function validate(req) {
    return twilio.validateExpressRequest(req, process.env.TWILIO_AUTH_TOKEN);
}
```

**Comment by samcal** [comment]
Let's get PR #6 in before working on this, big-time refactor that would be a small headache to rebase.

**Comment by DanielKerrigan** [comment]
I made the changes in my past two commits. I also updated the tests, but I am not positive that I did it correctly.

**Comment by samcal** [comment]
Looks good to me!
